apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: kubelet-restart-ansible
  namespace: litmus
spec:
  definition:
    scope: Cluster
    permissions:
      - apiGroups: [""]
        resources: ["pods", "nodes"]
        verbs: ["get", "list", "patch", "delete"]
    image: litmuschaos/ansible-runner:2.7.0
    args:
      - "-c"
      - |
        git clone https://github.com/balarobin/ansiblelitmus /litmus-ansible &&
        ansible-playbook /litmus-ansible/kubelet-restart.yaml -i /litmus-ansible/inventory/hosts
    command:
      - /bin/bash
    env:
      - name: ANSIBLE_FORCE_COLOR
        value: "true"
