apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: restart-kubelet
  labels:
    app.kubernetes.io/name: restart-kubelet
    app.kubernetes.io/part-of: litmus
spec:
  definition:
    scope: Cluster
    permissions:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["list", "get", "create", "delete"]
      - apiGroups: ["apps"]
        resources: ["deployments"]
        verbs: ["list", "get"]
    image: litmuschaos/ansible-runner:latest
    args:
      - -c
      - ansible-playbook /chaoslib/restart-kubelet.yaml -i /inventory/hosts
    command:
      - /bin/bash
    env:
      - name: ANSIBLE_STDOUT_CALLBACK
        value: "default"
    labels:
      name: restart-kubelet
    configmaps:
      - name: restart-kubelet-cm
        mountPath: /chaoslib
    secrets:
      - name: ansible-inventory
        mountPath: /inventory
    imagePullPolicy: Always
