apiVersion: litmuschaos.io/v1alpha1
kind: ChaosHub
metadata:
  name: raja
  labels:
    version: v1
spec:
  source:
    git:
      repoURL: "https://github.com/balarobin/ansiblelitmus.git" # Replace with your repo URL
      branch: "main" # Or your main branch name
