apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: kubelet-restart
  labels:
    app.kubernetes.io/component: experiment-template
    vendor: your-org
    version: v1
    category: kubelet
    maturity: alpha
    "litmuschaos.io/experiment": kubelet-restart
spec:
  definition:
    scope: Node
    permissions:
      - apiGroups: [""]
        resources: ["nodes"]
        verbs: ["get", "patch"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["create", "patch"]
    image: "litmuschaos/go-runner:latest" # Replace with your runner image
    imagePullPolicy: Always
    args:
    - -c
    - |
      #!/bin/bash -e
      echo "[INFO]: Restarting Kubelet on node: $NODE_NAME"
      set -o pipefail
      if [[ "$(which systemctl)" ]]; then
        systemctl restart kubelet
      elif [[ "$(which service)" ]]; then
        service kubelet restart
      else
        echo "[ERROR]: Could not find systemctl or service command"
        exit 1
      fi
      echo "[INFO]: Kubelet restart initiated."
    env:
    - name: NODE_NAME
      value: "{{ .NodeName }}"
