apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: restart-kubelet-
  labels:
    workflows.argoproj.io/controller-instanceid: litmus
    chaos.litmuschaos.io/metadata.type: workflow
spec:
  entrypoint: restart-kubelet
  serviceAccountName: litmus
  templates:
    - name: restart-kubelet
      steps:
        - - name: run-chaos
            template: chaos

    - name: chaos
      container:
        image: litmuschaos/ansible-runner:latest
        command: ["/bin/bash"]
        args:
          - -c
          - |
            git clone https://github.com/balarobin/ansiblelitmus.git && \
            ansible-playbook ansiblelitmus/restart-kubelet.yaml
