apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: restart-kubelet-git
  labels:
    name: restart-kubelet-git
spec:
  definition:
    scope: Cluster
    permissions:
      - apiGroups: [""]
        resources: ["nodes"]
        verbs: ["get", "list", "patch"]
    image: litmuschaos/ansible-runner:latest
    args:
      - -c
      - |
        git clone https://github.com/balarobin/ansiblelitmus.git && \
        ansible-playbook ansiblelitmus/restart-kubelet.yaml
    command:
      - /bin/bash
