apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: restart-kubelet
  labels:
    app.kubernetes.io/part-of: litmus
spec:
  definition:
    scope: Cluster
    permissions:
      - apiGroups: [""]
        resources: ["nodes"]
        verbs: ["get", "list", "patch"]
    image: litmuschaos/ansible-runner:latest
    args:
      - ansible-playbook
      - ./restart-kubelet.yaml
    env:
      - name: TARGET_NODE
        value: "node-name"
