apiVersion: litmuschaos.io/v1alpha1
kind: ChaosWorkflow
metadata:
  name: restart-kubelet-workflow
  labels:
    litmuschaos.io/chaos-hub: "true"
spec:
  definition:
    steps:
      - name: restart-kubelet-step
        template:
          name: restart-kubelet
  templates:
    - name: restart-kubelet
      inputs:
        artifacts:
          - name: chaosExperiment
            path: /tmp/chaos-engine.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  name: restart-kubelet-engine
                  namespace: litmus
                spec:
                  appinfo:
                    appns: default
                    applabel: ""
                    appkind: ""
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: restart-kubelet
                      spec:
                        components:
                          env:
                            - name: TARGET_NODE
                              value: "node-name"
      container:
        image: litmuschaos/litmus-checker:latest
        command: ["/bin/bash"]
        args: ["-c", "echo Running restart-kubelet experiment"]
